{
    "getException": {
        "name": "getException",
        "pos": [
            425,
            429
        ],
        "children": [
            {
                "name": "ReturnStatement",
                "pos": [
                    426,
                    427
                ],
                "children": [],
                "instructions": [
                    [
                        "0",
                        "aload_0"
                    ],
                    [
                        "1",
                        "getfield"
                    ],
                    [
                        "2",
                        "org/apache/commons/math3/ode/events/EventState$LocalMaxCountExceededException.wrapped:Lorg/apache/commons/math3/exception/MaxCountExceededException;"
                    ],
                    [
                        "4",
                        "areturn"
                    ]
                ]
            }
        ]
    }
}